---
  - name: Mongo | Check mongo_version variable
    assert:
      that: mongo_version in [ "2.6", "3" ]
    tags: 
       -mongo
     

  - include: "{{root_dir}}/tasks_mongodb_2.6.yml"
    when: mongo_version == "2.6"

  - include: "{{root_dir}}/tasks_mongodb_3.yml"
    when: mongo_version == "3"

