---
  - name: Mongo | Check mongo_version variable
    assert:
      that: mongo_version in [ "2.6", "3" ]
    tags: 
       -mongo

  - name: Include release related vars
    include_vars: "{{ item }}"
    with_first_found:
     - "{{root_dir}}/defaults/{{ansible_distribution_release}}_vars.yml"
     - "{{root_dir}}/defaults/default_vars.yml"
     

  - include: tasks_mongodb_2.6.yml
    when: mongo_version == "2.6"

  - include: tasks_mongodb_3.yml
    when: mongo_version == "3"

  - include: mongo_cfg_patch.yml
