---
  - name: Mongo | Check mongo_version variable
    assert:
      that: mongo_version in [ "2.6", "3", "3.2" ]
    tags: 
       -mongo
  
  - include: __detect_init_system.yml

  - name: Include release related vars
    include_vars: "{{ item }}"
    with_first_found:
     - "{{root_dir}}/defaults/{{ansible_distribution_release}}_vars.yml"
     - "{{root_dir}}/defaults/default_vars.yml"
     

  - include: tasks_mongodb_2.6.yml
    when: mongo_version == "2.6"

  - include: tasks_mongodb_3.yml
    when: mongo_version == "3"

  - include: tasks_mongodb_32.yml
    when: mongo_version == "3.2"

  - include: mongo_cfg_patch.yml
