---
- hosts: www

  vars:
    - root_dir: ..
    - custom_mongodb_family: "org"
    - custom_mongodb_version: "3.4"


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-mongo",
         mongo_version: "{{custom_mongodb_version}}",
         mongo_bind_ip: "0.0.0.0",
         mongo_family:  "{{custom_mongodb_family}}"
       }


  tasks:
    - debug: msg="Tasks section"
