---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-mongo",
         mongo_version: "3.2",
         mongo_bind_ip: "0.0.0.0"
       }


  tasks:
    - debug: msg="Tasks section"
